"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-06 22:16:18.313548

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contas",
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("ativa", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contas")),
        sa.UniqueConstraint("public_id", name=op.f("uq_contas_public_id")),
    )
    op.create_table(
        "clinicas",
        sa.Column("conta_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column(
            "fuso_horario", sa.String(length=64), server_default="America/Maceio", nullable=False
        ),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("endereco", sa.String(length=255), nullable=True),
        sa.Column("cidade", sa.String(length=100), nullable=True),
        sa.Column("uf", sa.CHAR(length=2), nullable=True),
        sa.Column("ativa", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conta_id"],
            ["contas.id"],
            name=op.f("fk_clinicas_conta_id_contas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinicas")),
        sa.UniqueConstraint("conta_id", "nome", name=op.f("uq_clinicas_conta_id_nome")),
        sa.UniqueConstraint("public_id", name=op.f("uq_clinicas_public_id")),
    )
    op.create_table(
        "servicos",
        sa.Column("conta_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column(
            "modalidade",
            sa.Enum("individual", "grupo", name="modalidade_servico"),
            server_default="individual",
            nullable=False,
        ),
        sa.Column(
            "duracao_minutos", sa.SmallInteger(), server_default=sa.text("50"), nullable=False
        ),
        sa.Column(
            "capacidade_padrao", sa.SmallInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("preco_mensalidade_centavos", sa.Integer(), nullable=True),
        sa.Column("preco_sessao_centavos", sa.Integer(), nullable=True),
        sa.Column("cor", sa.CHAR(length=7), server_default="#3B82F6", nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("excluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("capacidade_padrao > 0", name=op.f("ck_servicos_capacidade_positiva")),
        sa.CheckConstraint("duracao_minutos > 0", name=op.f("ck_servicos_duracao_positiva")),
        sa.CheckConstraint(
            "preco_mensalidade_centavos IS NULL OR preco_mensalidade_centavos >= 0",
            name=op.f("ck_servicos_preco_mensalidade_nao_negativo"),
        ),
        sa.CheckConstraint(
            "preco_sessao_centavos IS NULL OR preco_sessao_centavos >= 0",
            name=op.f("ck_servicos_preco_sessao_nao_negativo"),
        ),
        sa.ForeignKeyConstraint(
            ["conta_id"],
            ["contas.id"],
            name=op.f("fk_servicos_conta_id_contas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_servicos")),
        sa.UniqueConstraint("conta_id", "nome", name=op.f("uq_servicos_conta_id_nome")),
        sa.UniqueConstraint("public_id", name=op.f("uq_servicos_public_id")),
    )
    op.create_table(
        "usuarios",
        sa.Column("conta_id", sa.BigInteger(), nullable=False),
        sa.Column("keycloak_id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("e_profissional", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("registro_conselho", sa.String(length=30), nullable=True),
        sa.Column("especialidade", sa.String(length=120), nullable=True),
        sa.Column("cor_agenda", sa.CHAR(length=7), nullable=True),
        sa.Column("dono_da_conta", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("ultimo_login_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("excluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conta_id"],
            ["contas.id"],
            name=op.f("fk_usuarios_conta_id_contas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("conta_id", "email", name=op.f("uq_usuarios_conta_id_email")),
        sa.UniqueConstraint("keycloak_id", name=op.f("uq_usuarios_keycloak_id")),
        sa.UniqueConstraint("public_id", name=op.f("uq_usuarios_public_id")),
    )
    op.create_table(
        "bloqueios_agenda",
        sa.Column("clinica_id", sa.BigInteger(), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "ferias",
                "feriado",
                "licenca",
                "pessoal",
                "clinica_fechada",
                "outro",
                name="tipo_bloqueio",
            ),
            server_default="outro",
            nullable=False,
        ),
        sa.Column("inicio_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fim_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("motivo", sa.String(length=200), nullable=True),
        sa.Column("criado_por_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("fim_em > inicio_em", name=op.f("ck_bloqueios_agenda_intervalo_valido")),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas.id"],
            name=op.f("fk_bloqueios_agenda_clinica_id_clinicas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_bloqueios_agenda_criado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_bloqueios_agenda_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bloqueios_agenda")),
        sa.UniqueConstraint("public_id", name=op.f("uq_bloqueios_agenda_public_id")),
    )
    op.create_index(
        "ix_bloqueios_agenda_clinica_inicio",
        "bloqueios_agenda",
        ["clinica_id", "inicio_em"],
        unique=False,
    )
    op.create_index(
        "ix_bloqueios_agenda_usuario_inicio",
        "bloqueios_agenda",
        ["usuario_id", "inicio_em"],
        unique=False,
    )
    op.create_table(
        "clinica_usuarios",
        sa.Column("clinica_id", sa.BigInteger(), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "papel",
            sa.Enum("administrador", "comum", name="papel_usuario"),
            server_default="comum",
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas.id"],
            name=op.f("fk_clinica_usuarios_clinica_id_clinicas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_clinica_usuarios_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinica_usuarios")),
        sa.UniqueConstraint(
            "clinica_id", "usuario_id", name=op.f("uq_clinica_usuarios_clinica_id_usuario_id")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_clinica_usuarios_public_id")),
    )
    op.create_index(
        "ix_clinica_usuarios_usuario_id", "clinica_usuarios", ["usuario_id"], unique=False
    )
    op.create_table(
        "horarios_profissional",
        sa.Column("clinica_id", sa.BigInteger(), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("dia_semana", sa.SmallInteger(), nullable=False),
        sa.Column("hora_inicio", sa.Time(), nullable=False),
        sa.Column("hora_fim", sa.Time(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "dia_semana BETWEEN 0 AND 6", name=op.f("ck_horarios_profissional_dia_semana_valido")
        ),
        sa.CheckConstraint(
            "hora_fim > hora_inicio", name=op.f("ck_horarios_profissional_intervalo_valido")
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas.id"],
            name=op.f("fk_horarios_profissional_clinica_id_clinicas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_horarios_profissional_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_horarios_profissional")),
        sa.UniqueConstraint("public_id", name=op.f("uq_horarios_profissional_public_id")),
    )
    op.create_index(
        "ix_horarios_profissional_clinica_usuario_dia",
        "horarios_profissional",
        ["clinica_id", "usuario_id", "dia_semana"],
        unique=False,
    )
    op.create_table(
        "pacientes",
        sa.Column("conta_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("data_nascimento", sa.Date(), nullable=True),
        sa.Column("sexo", sa.String(length=20), nullable=True),
        sa.Column("cpf", sa.String(length=11), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("endereco", sa.String(length=255), nullable=True),
        sa.Column("cidade", sa.String(length=100), nullable=True),
        sa.Column("uf", sa.CHAR(length=2), nullable=True),
        sa.Column("contato_emergencia_nome", sa.String(length=150), nullable=True),
        sa.Column("contato_emergencia_telefone", sa.String(length=20), nullable=True),
        sa.Column("profissao", sa.String(length=120), nullable=True),
        sa.Column("encaminhado_por", sa.String(length=150), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("criado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("excluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conta_id"],
            ["contas.id"],
            name=op.f("fk_pacientes_conta_id_contas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_pacientes_criado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pacientes")),
        sa.UniqueConstraint("conta_id", "cpf", name=op.f("uq_pacientes_conta_id_cpf")),
        sa.UniqueConstraint("public_id", name=op.f("uq_pacientes_public_id")),
    )
    op.create_index("ix_pacientes_conta_nome", "pacientes", ["conta_id", "nome"], unique=False)
    op.create_table(
        "profissional_servicos",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("servico_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["servico_id"],
            ["servicos.id"],
            name=op.f("fk_profissional_servicos_servico_id_servicos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_profissional_servicos_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profissional_servicos")),
        sa.UniqueConstraint("public_id", name=op.f("uq_profissional_servicos_public_id")),
        sa.UniqueConstraint(
            "usuario_id", "servico_id", name=op.f("uq_profissional_servicos_usuario_id_servico_id")
        ),
    )
    op.create_table(
        "turmas",
        sa.Column("clinica_id", sa.BigInteger(), nullable=False),
        sa.Column("servico_id", sa.BigInteger(), nullable=False),
        sa.Column("profissional_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=True),
        sa.Column("dias_semana", postgresql.ARRAY(sa.SmallInteger()), nullable=False),
        sa.Column("hora_inicio", sa.Time(), nullable=False),
        sa.Column("duracao_minutos", sa.SmallInteger(), nullable=False),
        sa.Column("capacidade", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("inicio_em", sa.Date(), nullable=False),
        sa.Column("fim_em", sa.Date(), nullable=True),
        sa.Column("ativa", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("criado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacidade > 0", name=op.f("ck_turmas_capacidade_positiva")),
        sa.CheckConstraint("duracao_minutos > 0", name=op.f("ck_turmas_duracao_positiva")),
        sa.CheckConstraint(
            "fim_em IS NULL OR fim_em >= inicio_em", name=op.f("ck_turmas_vigencia_valida")
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas.id"],
            name=op.f("fk_turmas_clinica_id_clinicas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_turmas_criado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["usuarios.id"],
            name=op.f("fk_turmas_profissional_id_usuarios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["servico_id"],
            ["servicos.id"],
            name=op.f("fk_turmas_servico_id_servicos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turmas")),
        sa.UniqueConstraint("public_id", name=op.f("uq_turmas_public_id")),
    )
    op.create_index("ix_turmas_clinica_ativa", "turmas", ["clinica_id", "ativa"], unique=False)
    op.create_table(
        "agendamentos",
        sa.Column("clinica_id", sa.BigInteger(), nullable=False),
        sa.Column("servico_id", sa.BigInteger(), nullable=False),
        sa.Column("profissional_id", sa.BigInteger(), nullable=False),
        sa.Column("turma_id", sa.BigInteger(), nullable=True),
        sa.Column("inicio_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fim_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacidade", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "agendado",
                "confirmado",
                "realizado",
                "cancelado",
                "remarcado",
                "falta_profissional",
                name="status_agendamento",
            ),
            server_default="agendado",
            nullable=False,
        ),
        sa.Column("remarcado_de_id", sa.BigInteger(), nullable=True),
        sa.Column("remarcado_para_id", sa.BigInteger(), nullable=True),
        sa.Column("motivo_cancelamento", sa.String(length=255), nullable=True),
        sa.Column("cancelado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("criado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacidade > 0", name=op.f("ck_agendamentos_capacidade_positiva")),
        sa.CheckConstraint("fim_em > inicio_em", name=op.f("ck_agendamentos_intervalo_valido")),
        sa.ForeignKeyConstraint(
            ["cancelado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_agendamentos_cancelado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas.id"],
            name=op.f("fk_agendamentos_clinica_id_clinicas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_agendamentos_criado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["usuarios.id"],
            name=op.f("fk_agendamentos_profissional_id_usuarios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["remarcado_de_id"],
            ["agendamentos.id"],
            name=op.f("fk_agendamentos_remarcado_de_id_agendamentos"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["remarcado_para_id"],
            ["agendamentos.id"],
            name=op.f("fk_agendamentos_remarcado_para_id_agendamentos"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["servico_id"],
            ["servicos.id"],
            name=op.f("fk_agendamentos_servico_id_servicos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turma_id"],
            ["turmas.id"],
            name=op.f("fk_agendamentos_turma_id_turmas"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agendamentos")),
        sa.UniqueConstraint("public_id", name=op.f("uq_agendamentos_public_id")),
    )
    op.create_index(
        "ix_agendamentos_clinica_inicio", "agendamentos", ["clinica_id", "inicio_em"], unique=False
    )
    op.create_index(
        "ix_agendamentos_profissional_inicio",
        "agendamentos",
        ["profissional_id", "inicio_em"],
        unique=False,
    )
    op.create_index(
        "ix_agendamentos_servico_inicio", "agendamentos", ["servico_id", "inicio_em"], unique=False
    )
    op.create_index("ix_agendamentos_status", "agendamentos", ["status"], unique=False)
    op.create_index(
        "ix_agendamentos_turma_inicio", "agendamentos", ["turma_id", "inicio_em"], unique=False
    )
    op.create_table(
        "contratos",
        sa.Column("clinica_id", sa.BigInteger(), nullable=False),
        sa.Column("paciente_id", sa.BigInteger(), nullable=False),
        sa.Column("servico_id", sa.BigInteger(), nullable=False),
        sa.Column("valor_mensalidade_centavos", sa.Integer(), nullable=False),
        sa.Column(
            "dia_vencimento", sa.SmallInteger(), server_default=sa.text("10"), nullable=False
        ),
        sa.Column("sessoes_por_semana", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ativo", "suspenso", "encerrado", name="status_contrato"),
            server_default="ativo",
            nullable=False,
        ),
        sa.Column("inicio_em", sa.Date(), nullable=False),
        sa.Column("fim_em", sa.Date(), nullable=True),
        sa.Column("motivo_encerramento", sa.String(length=200), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("criado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dia_vencimento BETWEEN 1 AND 31", name=op.f("ck_contratos_dia_vencimento_valido")
        ),
        sa.CheckConstraint(
            "fim_em IS NULL OR fim_em >= inicio_em", name=op.f("ck_contratos_vigencia_valida")
        ),
        sa.CheckConstraint(
            "valor_mensalidade_centavos >= 0", name=op.f("ck_contratos_valor_nao_negativo")
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas.id"],
            name=op.f("fk_contratos_clinica_id_clinicas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_contratos_criado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["pacientes.id"],
            name=op.f("fk_contratos_paciente_id_pacientes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["servico_id"],
            ["servicos.id"],
            name=op.f("fk_contratos_servico_id_servicos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contratos")),
        sa.UniqueConstraint("public_id", name=op.f("uq_contratos_public_id")),
    )
    op.create_index(
        "ix_contratos_clinica_status", "contratos", ["clinica_id", "status"], unique=False
    )
    op.create_index(
        "ix_contratos_paciente_status", "contratos", ["paciente_id", "status"], unique=False
    )
    op.create_table(
        "pontos_atencao",
        sa.Column("paciente_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "gravidade",
            sa.Enum("info", "atencao", "critico", name="gravidade_ponto_atencao"),
            server_default="atencao",
            nullable=False,
        ),
        sa.Column("titulo", sa.String(length=120), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("criado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("resolvido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_pontos_atencao_criado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["pacientes.id"],
            name=op.f("fk_pontos_atencao_paciente_id_pacientes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pontos_atencao")),
        sa.UniqueConstraint("public_id", name=op.f("uq_pontos_atencao_public_id")),
    )
    op.create_index(
        "ix_pontos_atencao_paciente_ativo", "pontos_atencao", ["paciente_id", "ativo"], unique=False
    )
    op.create_table(
        "turma_alunos",
        sa.Column("turma_id", sa.BigInteger(), nullable=False),
        sa.Column("paciente_id", sa.BigInteger(), nullable=False),
        sa.Column("entrou_em", sa.Date(), nullable=False),
        sa.Column("saiu_em", sa.Date(), nullable=True),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "saiu_em IS NULL OR saiu_em >= entrou_em", name=op.f("ck_turma_alunos_periodo_valido")
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["pacientes.id"],
            name=op.f("fk_turma_alunos_paciente_id_pacientes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["turma_id"],
            ["turmas.id"],
            name=op.f("fk_turma_alunos_turma_id_turmas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turma_alunos")),
        sa.UniqueConstraint("public_id", name=op.f("uq_turma_alunos_public_id")),
        sa.UniqueConstraint(
            "turma_id", "paciente_id", name=op.f("uq_turma_alunos_turma_id_paciente_id")
        ),
    )
    op.create_index("ix_turma_alunos_paciente_id", "turma_alunos", ["paciente_id"], unique=False)
    op.create_table(
        "agendamento_pacientes",
        sa.Column("agendamento_id", sa.BigInteger(), nullable=False),
        sa.Column("paciente_id", sa.BigInteger(), nullable=False),
        sa.Column("contrato_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "agendado",
                "confirmado",
                "presente",
                "falta_paciente",
                "cancelado",
                "remarcado",
                name="status_participacao",
            ),
            server_default="agendado",
            nullable=False,
        ),
        sa.Column("remarcado_para_agendamento_id", sa.BigInteger(), nullable=True),
        sa.Column("motivo_cancelamento", sa.String(length=255), nullable=True),
        sa.Column("chegou_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agendamento_id"],
            ["agendamentos.id"],
            name=op.f("fk_agendamento_pacientes_agendamento_id_agendamentos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contrato_id"],
            ["contratos.id"],
            name=op.f("fk_agendamento_pacientes_contrato_id_contratos"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["pacientes.id"],
            name=op.f("fk_agendamento_pacientes_paciente_id_pacientes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["remarcado_para_agendamento_id"],
            ["agendamentos.id"],
            name=op.f("fk_agendamento_pacientes_remarcado_para_agendamento_id_agendamentos"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agendamento_pacientes")),
        sa.UniqueConstraint(
            "agendamento_id",
            "paciente_id",
            name=op.f("uq_agendamento_pacientes_agendamento_id_paciente_id"),
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_agendamento_pacientes_public_id")),
    )
    op.create_index(
        "ix_agendamento_pacientes_contrato_id",
        "agendamento_pacientes",
        ["contrato_id"],
        unique=False,
    )
    op.create_index(
        "ix_agendamento_pacientes_paciente_criado",
        "agendamento_pacientes",
        ["paciente_id", "criado_em"],
        unique=False,
    )
    op.create_index(
        "ix_agendamento_pacientes_status", "agendamento_pacientes", ["status"], unique=False
    )
    op.create_table(
        "cobrancas",
        sa.Column("clinica_id", sa.BigInteger(), nullable=False),
        sa.Column("paciente_id", sa.BigInteger(), nullable=False),
        sa.Column("contrato_id", sa.BigInteger(), nullable=True),
        sa.Column("competencia", sa.Date(), nullable=True),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("valor_centavos", sa.Integer(), nullable=False),
        sa.Column("desconto_centavos", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("acrescimo_centavos", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("valor_pago_centavos", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vence_em", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("aberta", "parcial", "paga", "cancelada", name="status_cobranca"),
            server_default="aberta",
            nullable=False,
        ),
        sa.Column("quitada_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("criado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acrescimo_centavos >= 0", name=op.f("ck_cobrancas_acrescimo_nao_negativo")
        ),
        sa.CheckConstraint(
            "desconto_centavos >= 0", name=op.f("ck_cobrancas_desconto_nao_negativo")
        ),
        sa.CheckConstraint("valor_centavos >= 0", name=op.f("ck_cobrancas_valor_nao_negativo")),
        sa.CheckConstraint(
            "valor_pago_centavos >= 0", name=op.f("ck_cobrancas_valor_pago_nao_negativo")
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas.id"],
            name=op.f("fk_cobrancas_clinica_id_clinicas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contrato_id"],
            ["contratos.id"],
            name=op.f("fk_cobrancas_contrato_id_contratos"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_cobrancas_criado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["pacientes.id"],
            name=op.f("fk_cobrancas_paciente_id_pacientes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cobrancas")),
        sa.UniqueConstraint(
            "contrato_id", "competencia", name=op.f("uq_cobrancas_contrato_id_competencia")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_cobrancas_public_id")),
    )
    op.create_index(
        "ix_cobrancas_clinica_vence", "cobrancas", ["clinica_id", "vence_em"], unique=False
    )
    op.create_index(
        "ix_cobrancas_paciente_status", "cobrancas", ["paciente_id", "status"], unique=False
    )
    op.create_index("ix_cobrancas_status_vence", "cobrancas", ["status", "vence_em"], unique=False)
    op.create_table(
        "evolucoes",
        sa.Column("paciente_id", sa.BigInteger(), nullable=False),
        sa.Column("agendamento_paciente_id", sa.BigInteger(), nullable=True),
        sa.Column("profissional_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "avaliacao", "evolucao", "reavaliacao", "alta", "anotacao", name="tipo_evolucao"
            ),
            server_default="evolucao",
            nullable=False,
        ),
        sa.Column("realizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("queixa", sa.Text(), nullable=True),
        sa.Column("avaliacao", sa.Text(), nullable=True),
        sa.Column("conduta", sa.Text(), nullable=True),
        sa.Column("evolucao", sa.Text(), nullable=True),
        sa.Column("pontos_atencao", sa.Text(), nullable=True),
        sa.Column("plano_proxima_sessao", sa.Text(), nullable=True),
        sa.Column("escala_dor", sa.SmallInteger(), nullable=True),
        sa.Column("assinado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "escala_dor IS NULL OR escala_dor BETWEEN 0 AND 10",
            name=op.f("ck_evolucoes_escala_dor_valida"),
        ),
        sa.ForeignKeyConstraint(
            ["agendamento_paciente_id"],
            ["agendamento_pacientes.id"],
            name=op.f("fk_evolucoes_agendamento_paciente_id_agendamento_pacientes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["pacientes.id"],
            name=op.f("fk_evolucoes_paciente_id_pacientes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["usuarios.id"],
            name=op.f("fk_evolucoes_profissional_id_usuarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evolucoes")),
        sa.UniqueConstraint(
            "agendamento_paciente_id", name=op.f("uq_evolucoes_agendamento_paciente_id")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_evolucoes_public_id")),
    )
    op.create_index(
        "ix_evolucoes_paciente_realizado",
        "evolucoes",
        ["paciente_id", "realizado_em"],
        unique=False,
    )
    op.create_index(
        "ix_evolucoes_profissional_realizado",
        "evolucoes",
        ["profissional_id", "realizado_em"],
        unique=False,
    )
    op.create_table(
        "pagamentos",
        sa.Column("cobranca_id", sa.BigInteger(), nullable=False),
        sa.Column("valor_centavos", sa.Integer(), nullable=False),
        sa.Column(
            "forma",
            sa.Enum(
                "dinheiro",
                "pix",
                "debito",
                "credito",
                "transferencia",
                "outro",
                name="forma_pagamento",
            ),
            server_default="pix",
            nullable=False,
        ),
        sa.Column("pago_em", sa.Date(), nullable=False),
        sa.Column("observacoes", sa.String(length=255), nullable=True),
        sa.Column("estornado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registrado_por_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("valor_centavos >= 0", name=op.f("ck_pagamentos_valor_nao_negativo")),
        sa.ForeignKeyConstraint(
            ["cobranca_id"],
            ["cobrancas.id"],
            name=op.f("fk_pagamentos_cobranca_id_cobrancas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por_id"],
            ["usuarios.id"],
            name=op.f("fk_pagamentos_registrado_por_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pagamentos")),
        sa.UniqueConstraint("public_id", name=op.f("uq_pagamentos_public_id")),
    )
    op.create_index("ix_pagamentos_cobranca_id", "pagamentos", ["cobranca_id"], unique=False)
    op.create_index("ix_pagamentos_pago_em", "pagamentos", ["pago_em"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pagamentos_pago_em", table_name="pagamentos")
    op.drop_index("ix_pagamentos_cobranca_id", table_name="pagamentos")
    op.drop_table("pagamentos")
    op.drop_index("ix_evolucoes_profissional_realizado", table_name="evolucoes")
    op.drop_index("ix_evolucoes_paciente_realizado", table_name="evolucoes")
    op.drop_table("evolucoes")
    op.drop_index("ix_cobrancas_status_vence", table_name="cobrancas")
    op.drop_index("ix_cobrancas_paciente_status", table_name="cobrancas")
    op.drop_index("ix_cobrancas_clinica_vence", table_name="cobrancas")
    op.drop_table("cobrancas")
    op.drop_index("ix_agendamento_pacientes_status", table_name="agendamento_pacientes")
    op.drop_index("ix_agendamento_pacientes_paciente_criado", table_name="agendamento_pacientes")
    op.drop_index("ix_agendamento_pacientes_contrato_id", table_name="agendamento_pacientes")
    op.drop_table("agendamento_pacientes")
    op.drop_index("ix_turma_alunos_paciente_id", table_name="turma_alunos")
    op.drop_table("turma_alunos")
    op.drop_index("ix_pontos_atencao_paciente_ativo", table_name="pontos_atencao")
    op.drop_table("pontos_atencao")
    op.drop_index("ix_contratos_paciente_status", table_name="contratos")
    op.drop_index("ix_contratos_clinica_status", table_name="contratos")
    op.drop_table("contratos")
    op.drop_index("ix_agendamentos_turma_inicio", table_name="agendamentos")
    op.drop_index("ix_agendamentos_status", table_name="agendamentos")
    op.drop_index("ix_agendamentos_servico_inicio", table_name="agendamentos")
    op.drop_index("ix_agendamentos_profissional_inicio", table_name="agendamentos")
    op.drop_index("ix_agendamentos_clinica_inicio", table_name="agendamentos")
    op.drop_table("agendamentos")
    op.drop_index("ix_turmas_clinica_ativa", table_name="turmas")
    op.drop_table("turmas")
    op.drop_table("profissional_servicos")
    op.drop_index("ix_pacientes_conta_nome", table_name="pacientes")
    op.drop_table("pacientes")
    op.drop_index(
        "ix_horarios_profissional_clinica_usuario_dia", table_name="horarios_profissional"
    )
    op.drop_table("horarios_profissional")
    op.drop_index("ix_clinica_usuarios_usuario_id", table_name="clinica_usuarios")
    op.drop_table("clinica_usuarios")
    op.drop_index("ix_bloqueios_agenda_usuario_inicio", table_name="bloqueios_agenda")
    op.drop_index("ix_bloqueios_agenda_clinica_inicio", table_name="bloqueios_agenda")
    op.drop_table("bloqueios_agenda")
    op.drop_table("usuarios")
    op.drop_table("servicos")
    op.drop_table("clinicas")
    op.drop_table("contas")
    # ### end Alembic commands ###

    # O autogenerate cria os tipos enum implicitamente no create_table, mas nao
    # os remove no downgrade. Sem isto, `downgrade base` deixa dez tipos orfaos
    # e o proximo `upgrade` falha com DuplicateObject.
    op.execute("DROP TYPE IF EXISTS papel_usuario")
    op.execute("DROP TYPE IF EXISTS modalidade_servico")
    op.execute("DROP TYPE IF EXISTS status_agendamento")
    op.execute("DROP TYPE IF EXISTS status_participacao")
    op.execute("DROP TYPE IF EXISTS tipo_evolucao")
    op.execute("DROP TYPE IF EXISTS gravidade_ponto_atencao")
    op.execute("DROP TYPE IF EXISTS tipo_bloqueio")
    op.execute("DROP TYPE IF EXISTS status_contrato")
    op.execute("DROP TYPE IF EXISTS status_cobranca")
    op.execute("DROP TYPE IF EXISTS forma_pagamento")
